# Sample BSD Makefile for a68g

CC=clang
CFLAGS=-Wall -g
INCDIR=./src/include
LDFLAGS=-lm -lpthread
BINARY=a68g
SOURCES!=ls ./src/a68g/*.c
OBJECTS=${SOURCES:.c=.o}

all: ${BINARY}

clean:
	rm -f ${BINARY} ${OBJECTS}

${BINARY}: ${OBJECTS}
	${CC} ${LDFLAGS} ${OBJECTS} -o ${BINARY}

.c.o:
	${CC} -DBUILD_BSD -I. -I${INCDIR} ${CFLAGS} -c ${.IMPSRC} -o ${.TARGET}

install:	${BINARY}
	cp ${TARGET} ${BINDIR}

uninstall:	${BINARY}
	rm ${BINDIR}/${BINDIR}
